# Generated by Django 4.1.7 on 2023-06-21 22:12

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_description_alter_posts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=models.ImageField(upload_to=posts.models.user_directory_path),
        ),
    ]
