# Generated by Django 4.1.7 on 2023-03-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('TI', 'TARJETA DE IDENTIDAD'), ('IT', 'IDENTIFICACION TRIBUTARIA'), ('IP', 'IDENTIFICACION PERSONAL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
