# Generated by Django 4.1.7 on 2023-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_alter_profileuser_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='document_type',
            field=models.CharField(blank=True, choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('TI', 'TARJETA DE IDENTIDAD'), ('IT', 'IDENTIFICACION TRIBUTARIA'), ('IP', 'IDENTIFICACION PERSONAL')], default='CC', max_length=50),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
