# Generated by Django 4.1.7 on 2023-03-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_alter_profileuser_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='document_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
