# Generated by Django 4.1.7 on 2023-03-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0004_alter_profileuser_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
