# Generated by Django 4.1.7 on 2023-05-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0005_alter_profileuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDataBeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('TI', 'TARJETA DE IDENTIDAD'), ('IT', 'IDENTIFICACION TRIBUTARIA'), ('IP', 'IDENTIFICACION PERSONAL')], default='CC', max_length=3)),
                ('document_number', models.CharField(error_messages={'unique': 'Documento está registrado'}, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('occupation', models.TextField(max_length=250)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
