# Generated by Django 4.1.7 on 2023-05-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0006_modeldatabeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldatabeta',
            name='document_type',
            field=models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('IP', 'IDENTIFICACION PERSONAL')], default='CC', max_length=3),
        ),
    ]
