# Generated by Django 4.1.7 on 2023-06-21 16:50

from django.db import migrations, models
import profile_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0007_alter_modeldatabeta_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='biography',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='document_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='document_type',
            field=models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('TI', 'TARJETA DE IDENTIDAD'), ('IT', 'IDENTIFICACION TRIBUTARIA'), ('IP', 'IDENTIFICACION PERSONAL')], default='CC', max_length=50),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='picture',
            field=models.ImageField(upload_to=profile_user.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
