# Generated by Django 4.1.7 on 2023-06-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0008_alter_profileuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='document_type',
            field=models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('TI', 'TARJETA DE IDENTIDAD'), ('IT', 'IDENTIFICACION TRIBUTARIA'), ('IP', 'IDENTIFICACION PERSONAL')], default='CC', max_length=50, verbose_name='Docuemnto'),
        ),
    ]
