# Generated by Django 4.1.7 on 2023-06-21 22:36

import django.core.validators
from django.db import migrations, models
import profile_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0009_alter_profileuser_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='biography',
            field=models.TextField(max_length=150, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='document_number',
            field=models.CharField(max_length=50, verbose_name='Numero de Documento'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='document_type',
            field=models.CharField(choices=[('CC', 'CEDULA DE CIUDADANIA'), ('CE', 'CEDULA DE EXTRANJERIA'), ('PA', 'PASAPORTE'), ('TI', 'TARJETA DE IDENTIDAD'), ('IT', 'IDENTIFICACION TRIBUTARIA'), ('IP', 'IDENTIFICACION PERSONAL')], default='CC', max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Numero de Telefono'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='picture',
            field=models.ImageField(upload_to=profile_user.models.user_directory_path, verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='website',
            field=models.CharField(max_length=200, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo'),
        ),
    ]
