# Generated by Django 4.1.7 on 2023-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0010_alter_profileuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Dirección de correo electrónico'),
        ),
    ]
